name: Feature request
description: Suggest an idea for Brickcard
labels: [enhancement]
assignees: [jo-m1b]
body:
  - type: textarea
    attributes:
      label: What would you like?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why do you need it?
  - type: markdown
    attributes:
      value: |
        ---
        > 👍 Before creating, check if [similar request exists](https://github.com/jo-m1b/brickcard/issues?q=is%3Aissue+label%3Aenhancement) and vote instead!
